
name: "Generate and Upload SBOM"
on: [push, pull_request, workflow_dispatch]

jobs:
  generate_sbom:
    runs-on: ubuntu-latest
    name: "SBOM Generation"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Generate SBOM
        id: generate-sbom-and-upload-to-sbom-com-tr
        uses: sbomtr/scan@0.1.1
        with:
          scanner_name: 'trivyfs'
          target: '.' # Assuming you want to scan the entire repository
  
      - name: Output SBOM URL
        run: echo "The SBOM can be found at $SBOM_SHARE_URL"
                    
